# Generated by Django 3.2.8 on 2021-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='Password',
            field=models.CharField(default='not available', max_length=100),
        ),
        migrations.AddField(
            model_name='model',
            name='Re_Enter_Password',
            field=models.CharField(default='not available', max_length=100),
        ),
    ]
