# Generated by Django 3.2.8 on 2021-10-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20211013_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='Re_Enter_Password',
            new_name='ReEnterPassword',
        ),
    ]
